# Generated by Django 3.2.5 on 2021-07-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('rigor', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('precisao', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('profundidade', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('amplitude', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('logica', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('significancia', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('originalidade', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('visual', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('geral', models.CharField(choices=[('1', 'Mau'), ('2', 'Razoavel'), ('3', 'Bom'), ('4', 'Excelente')], default='Unspecified', max_length=1)),
                ('comment', models.CharField(blank=True, default='Comente aqui!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30)),
                ('telefone', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('p1', models.CharField(choices=[('1', 'Juventus🏳️'), ('2', 'Real Madrid🏳️'), ('3', 'M. United🏳️')], default='0', max_length=1)),
                ('p2', models.CharField(blank=True, choices=[('1', 'Jogador'), ('2', 'Treinador')], default='0', max_length=1)),
                ('p3', models.CharField(max_length=22, null=True)),
                ('p4', models.CharField(choices=[('1', '30000'), ('2', '40000'), ('3', '50000')], default='0', max_length=1)),
                ('p5', models.CharField(blank=True, choices=[('1', 'Real Madrid'), ('2', 'Sporting'), ('3', 'M.United'), ('4', 'Juventus')], default='0', max_length=1)),
                ('p6', models.CharField(blank=True, choices=[('1', 'Rui Costa'), ('2', 'S. Conceição'), ('3', 'Luís Figo')], default='0', max_length=1)),
                ('p7', models.IntegerField(default=0)),
                ('p8', models.TextField(max_length=10, null=True)),
                ('p9', models.CharField(choices=[('1', 'Sporting'), ('2', 'Benfica'), ('3', 'Porto')], default='0', max_length=1)),
                ('p10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cor1', models.CharField(max_length=7)),
                ('cor2', models.CharField(max_length=7)),
                ('cor3', models.CharField(max_length=7)),
                ('cor4', models.CharField(max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
                ('categoria', models.ManyToManyField(blank=True, related_name='Jogadores', to='website.Categoria')),
            ],
        ),
    ]
