# Generated by Django 3.2.5 on 2021-07-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210727_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apelido',
            field=models.CharField(default='Obrigatorio', max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(default='Obrigatorio', max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nome',
            field=models.CharField(default='Obrigatorio', max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='username',
            field=models.CharField(default='Obrigatorio', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='apelido',
            field=models.CharField(default='Obrigatorio', max_length=15),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='clube',
            field=models.CharField(default='Obrigatorio', max_length=50),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='contacto',
            field=models.ForeignKey(default='Obrigatorio', on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(default='Obrigatorio', max_length=15),
        ),
    ]
