# Generated by Django 3.2.5 on 2021-07-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210727_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='contacto',
            field=models.ForeignKey(default='Obrigatorio', on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
    ]
