# Generated by Django 3.2.5 on 2021-07-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_comentario_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='contacto',
            field=models.ForeignKey(default='Obrigatorio', on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
    ]
