# Generated by Django 3.2.5 on 2021-07-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_quizz_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='username',
            new_name='id',
        ),
    ]
