# Generated by Django 3.2.5 on 2021-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=15)),
                ('apelido', models.CharField(max_length=15)),
                ('clube', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=25)),
                ('jogador', models.ManyToManyField(blank=True, related_name='Jogadores', to='singlepage.Jogador')),
            ],
        ),
    ]
