# Generated by Django 3.2.5 on 2021-07-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
